<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIH-D-16328" ignored="0" name="_设备2_" tests="7" failures="1" timestamp="26 十二月 2018 02:28:04 GMT" time="311.509" errors="0">
  <testcase name="runCase" time="45.987" classname="com.netease.qa.ai.smartauto.runners.Runner12"/>
  <testcase name="runCase" time="27.996" classname="com.netease.qa.ai.smartauto.runners.Runner13"/>
  <testcase name="runCase" time="23.385" classname="com.netease.qa.ai.smartauto.runners.Runner14">
    <failure type="java.lang.AssertionError" message="执行失败或程序异常：存在操作时间。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=75813&amp;amp;device_id=3820">
      <![CDATA[java.lang.AssertionError: 执行失败或程序异常：存在操作时间。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=75813&device_id=3820
at com.netease.qa.ai.smartauto.runners.Runner14.runCase(Runner14.java:31)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- runCase -->
  <testcase name="runCase" time="142.344" classname="com.netease.qa.ai.smartauto.runners.Runner15"/>
  <testcase name="runCase" time="5.944" classname="com.netease.qa.ai.smartauto.runners.Runner16"/>
  <testcase name="runCase" time="28.577" classname="com.netease.qa.ai.smartauto.runners.Runner17"/>
  <testcase name="runCase" time="37.206" classname="com.netease.qa.ai.smartauto.runners.Runner18"/>
</testsuite> <!-- _设备2_ -->
